### ISSUE TITLE
debian/control: Minor issues

### ISSUE THREAD

**Issue by 12345ieee** [sriemer/scanmem-debian#1]
1. https://github.com/sriemer/scanmem-debian/blob/master/debian/control#L43: "CheatEngline" should be "CheatEngine".
2. I don't know the exact Debian guidelines, but wouldn't you want GC version x.y.z to depend exactly on scanmem x.y.z instead of scanmem >= x.y.0?

**Comment by sriemer** [comment]
Thanks for reporting the typo! With >= it is possible to update the dependency less frequently. Sometimes really nothing changes at the interfaces and it almost doesn't matter which versions are used. GC also warns if versions don't match. So it is okay this way.

**Comment by sriemer** [comment]
`= ${binary:Version}` is used now for the exact depend.

**Comment by 12345ieee** [comment]
👍
Let me know when/if you need testing.

**Comment by sriemer** [comment]
I'm almost done. Please feel free to review and test as well. Lintian is happy. It only warns about unneeded `ldconfig` invocation by `libtool` and about some dots in the scanmem man page which is a false-positive.

**Comment by 12345ieee** [comment]
I confirm the package builds correctly, I'll test it later.

I see your lintian warnings and also this set:
```
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/libscanmem1/usr/lib/scanmem/libscanmem.so.1.0.0 was not linked against libtinfo.so.5 (it uses none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/scanmem/usr/bin/scanmem was not linked against libreadline.so.7 (it uses none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/scanmem/usr/bin/scanmem was not linked against libtinfo.so.5 (it uses none of the library's symbols)
```

that I imagine it's another false positive, there's no way we don't need libreadline.

**Comment by sriemer** [comment]
Yes, that's a false positive. It only appears if scanmem is linked against absolute path of libscanmem.so.1 and that is the case here as /usr/lib/scanmem is not in the library search path. That's what the Debian release manager wants.

**Comment by 12345ieee** [comment]
What I find a tad strange is that libscanmem1 depends on 'libreadline7 (>= 6.0), libtinfo5 (>= 6)' as well, (at least, the control file in my built packages says that) which it shouldn't need.

Is this a packaging issue or do we need some refactoring upstream?

**Comment by sriemer** [comment]
libreadline7 depends on libtinfo5. This is normal and needed. Those depends are passed to `scanmem` due to linking. You can see it with `ldd` that these depends are required.

**Comment by 12345ieee** [comment]
That's ok, but I would expect only the front end (scanmem) to depend on libreadline (and by extension libtinfo), not libscanmem1 to depend on them and then transfer these dependencies down.

**Comment by sriemer** [comment]
`scanmem` should only depend on `libscanmem.so.1`. The source in `main.c` doesn't need any includes or functions from `libreadline`. But all required libraries are loaded into the executable and accessed from there. So yes, it is clear that the executable has all the depends the libs have.
This is how the dynamic loader `ld-linux.so` works.

See:
* cat /proc/`pidof scanmem`/maps
* ldd `which scanmem`
* man ld.so
