### ISSUE TITLE
Are we shipping binaries compiled with -g?

### ISSUE THREAD

**Issue by 12345ieee** [sriemer/scanmem-debian#2]
Shouldn't the debug flag be turned off? At least for the scanmem exe itself.

Debug symbols for libraries are a bit more complicated, too, but I don't know the specifics.

**Comment by sriemer** [comment]
`dh_strip` should handle that and put debug symbols in a separate package. I'll check that.

**Comment by sriemer** [comment]
I've checked that with `gdb`. It is like I said: `dh_strip` strips the debug symbols and puts them in a package "scanmem-dbgsym_$vers_$arch.deb". `(gdb) list *main` only works if the debug symbols are installed.

**Comment by 12345ieee** [comment]
Sorry, I was looking at `dpkg-buildpackage` output and saw `-g` used.
Didn't know that they would be stripped later.

~~I'm having problems building the deb, as `usr/include/scanmem/` doesn't seem to install correctly in fakeroot, even though the normal `make install` installation has them at the correct place.~~
Typos in the script...

**Comment by sriemer** [comment]
I prefer `sbuild`. That's what Debian and Ubuntu are using.
https://wiki.debian.org/sbuild
